name: loki-distributed
home: https://grafana.github.io/helm-charts
sources:
    - https://github.com/grafana/loki
    - https://grafana.com/docs/loki/latest/
    - https://grafana.com/oss/loki/
version: 0.79.3-1
description: Helm chart for Grafana Loki in microservices mode
keywords: []
maintainers:
    - name: unguiculus
      email: ""
      url: ""
icon: https://grafana.com/docs/loki/latest/logo_and_name.png
apiversion: v2
condition: ""
tags: ""
appversion: 2.9.8
deprecated: false
annotations: {}
kubeversion: ""
dependencies: []
type: application
